FROM node:lts-alpine
RUN yarn create koishi koishi -y
RUN cd koishi && yarn install --prod && yarn add @koishijs/plugin-database-sqlite -W
RUN sed -i 's/host: .*/host: 0.0.0.0/g' /koishi/koishi.yml

FROM node:lts-alpine
COPY --from=0 /koishi /home/koishi/koishi

RUN apk add --no-cache chromium nss freetype harfbuzz ca-certificates ttf-freefont font-noto-cjk
RUN adduser -D koishi
USER koishi

WORKDIR /home/koishi/koishi
ENTRYPOINT [ "yarn", "start" ]
