name: Sync

on:
  push:
    branches:
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Sync files
        run: bash .github/workflows/sync.sh

      - name: Deploy master
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          publish_dir: dist
          publish_branch: master
          # https://github.com/peaceiris/actions-gh-pages/issues/163
          exclude_assets: ''
          force_orphan: true
          enable_jekyll: true
          commit_message: '[skip ci] deploy'

      - name: Publish
        run: bash .github/workflows/publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
